language: python
python:
  - "2.7"
env: 
  global:
    - PORT=5000
    - DB_URL=mongodb://localhost:27017/fiuberdb-test
    - DB_NAME=fiuberdb-test
    - SECRET_KEY=umpalumpa
    - LOG_LEVEL=ERROR
    - TOKEN_DURATION=2
    - MONGODB_VERSION=2.6.10


notifications:
  email:  
     recipients:
       -  gonzalpetraglia@gmail.com
       -  santiago.v.gandolfo@gmail.com
       -  federicobalina@gmail.com
       -  christiangelone@gmail.com
     on_failure: always 
     on_success: change
install: 
  - pip install -r requirements.txt
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - tar xfz mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - export PATH=`pwd`/mongodb-linux-x86_64-$MONGODB_VERSION/bin:$PATH
  - mkdir -p data/db
  - mongod --dbpath=data/db &
  - sleep 3
before_script:
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script: 
  python manage.py cov

after_success:
  coveralls
