language: python
python:
  - "2.7"
notifications:
  email:  
     recipients:
       -  gonzalpetraglia@gmail.com
       -  santiago.v.gandolfo@gmail.com
     on_failure: always 
     on_success: change
install: "pip install -r requirements.txt"
script: pytest
