language: python
python:
  - "2.7"
notifications:
  email:  
     recipients:
       -  gonzalpetraglia@gmail.com
       -  santiago.v.gandolfo@gmail.com
       -  federicobalina@gmail.com
       -  christiangelone@gmail.com
     on_failure: always 
     on_success: change
install: "pip install -r requirements.txt"
script: 
  coverage run --source src/ -m pytest
  coverage report
after_success:
  coveralls
