language: python
python:
  - "2.7"
env: 
  - PORT=5000
notifications:
  email:  
     recipients:
       -  gonzalpetraglia@gmail.com
       -  santiago.v.gandolfo@gmail.com
       -  federicobalina@gmail.com
       -  christiangelone@gmail.com
     on_failure: always 
     on_success: change
install: "pip install -r requirements.txt"
script: 
  python manage.py test

after_success:
  coveralls
