.TH "src Directory Reference" 3 "Mon Nov 6 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBhandlers\fP"
.br
.ti -1c
.RI "directory \fBservices\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB__init__\&.py\fP"
.br
.ti -1c
.RI "file \fBexceptions\&.py\fP"
.br
.ti -1c
.RI "file \fBmodels\&.py\fP"
.br
.in -1c
