.TH "src/services Directory Reference" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/services Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB__init__\&.py\fP"
.br
.ti -1c
.RI "file \fBgoogle_maps\&.py\fP"
.br
.ti -1c
.RI "file \fBpush_notifications\&.py\fP"
.br
.ti -1c
.RI "file \fBshared_server\&.py\fP"
.br
.in -1c
