.TH "src/controllers/AppController.py" 3 "Sat Sep 9 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/controllers/AppController.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBserver\&.src\&.controllers\&.AppController\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBserver\&.src\&.controllers\&.AppController\&.index\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
