.TH "src/handlers/DriversHandler.py" 3 "Mon Nov 6 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/handlers/DriversHandler.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBserver\&.src\&.handlers\&.DriversHandler\&.DriversAPI\fP"
.br
.ti -1c
.RI "class \fBserver\&.src\&.handlers\&.DriversHandler\&.AvailableEndpoint\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBserver\&.src\&.handlers\&.DriversHandler\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBserver\&.src\&.handlers\&.DriversHandler\&.drivers_blueprint\fP = Blueprint('drivers', __name__)"
.br
.ti -1c
.RI "\fBserver\&.src\&.handlers\&.DriversHandler\&.drivers_view\fP = DriversAPI\&.as_view('drivers_api')"
.br
.ti -1c
.RI "\fBserver\&.src\&.handlers\&.DriversHandler\&.available_view\fP = AvailableEndpoint\&.as_view('available_endpoint')"
.br
.ti -1c
.RI "\fBserver\&.src\&.handlers\&.DriversHandler\&.view_func\fP"
.br
.ti -1c
.RI "\fBserver\&.src\&.handlers\&.DriversHandler\&.methods\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
