.TH "src/services/google_maps.py" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/services/google_maps.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBserver\&.src\&.services\&.google_maps\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBserver\&.src\&.services\&.google_maps\&.get_directions\fP (data)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBserver\&.src\&.services\&.google_maps\&.GOOGLE_KEY\fP = os\&.environ['GOOGLE_KEY']"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
