.TH "src/models.py" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/models.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBserver\&.src\&.models\&.User\fP"
.br
.ti -1c
.RI "class \fBserver\&.src\&.models\&.BlacklistToken\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBserver\&.src\&.models\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBserver\&.src\&.models\&.SECRET_KEY\fP = os\&.environ\&.get('SECRET_KEY', 'key')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
