.TH "src/services/push_notifications.py" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/services/push_notifications.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBserver\&.src\&.services\&.push_notifications\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBserver\&.src\&.services\&.push_notifications\&.send_push_notifications\fP (username, message_body, data_message)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBserver\&.src\&.services\&.push_notifications\&.FIREBASE_KEY\fP = os\&.environ['FIREBASE_KEY']"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
