.TH "src/handlers/SecurityHandler.py" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/handlers/SecurityHandler.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBserver\&.src\&.handlers\&.SecurityHandler\&.SecurityAPI\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBserver\&.src\&.handlers\&.SecurityHandler\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBserver\&.src\&.handlers\&.SecurityHandler\&.SECURITY_BLUEPRINT\fP = Blueprint('security', __name__)"
.br
.ti -1c
.RI "\fBserver\&.src\&.handlers\&.SecurityHandler\&.SECURITY_VIEW\fP = SecurityAPI\&.as_view('security_api')"
.br
.ti -1c
.RI "\fBserver\&.src\&.handlers\&.SecurityHandler\&.view_func\fP"
.br
.ti -1c
.RI "\fBserver\&.src\&.handlers\&.SecurityHandler\&.methods\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
