.TH "server.src.handlers.TripHandler" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.handlers.TripHandler \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTripsAPI\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBTRIPS_BLUEPRINT\fP = Blueprint('trips', __name__)"
.br
.ti -1c
.RI "\fBTRIPS_VIEW\fP = TripsAPI\&.as_view('trips_api')"
.br
.ti -1c
.RI "\fBview_func\fP"
.br
.ti -1c
.RI "\fBmethods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Handlers related with trips
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "server\&.src\&.handlers\&.TripHandler\&.methods"

.PP
Definition at line 187 of file TripHandler\&.py\&.
.SS "server\&.src\&.handlers\&.TripHandler\&.TRIPS_BLUEPRINT = Blueprint('trips', __name__)"

.PP
Definition at line 16 of file TripHandler\&.py\&.
.SS "server\&.src\&.handlers\&.TripHandler\&.TRIPS_VIEW = TripsAPI\&.as_view('trips_api')"

.PP
Definition at line 181 of file TripHandler\&.py\&.
.SS "server\&.src\&.handlers\&.TripHandler\&.view_func"

.PP
Definition at line 186 of file TripHandler\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
