.TH "server.src.handlers.DriversHandler.CarDeleteEndPoint" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.handlers.DriversHandler.CarDeleteEndPoint \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MethodView\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBdelete\fP (username, car_id)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
View used for deleting a car from a specific driver
.fi
.PP
 
.PP
Definition at line 135 of file DriversHandler\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def server\&.src\&.handlers\&.DriversHandler\&.CarDeleteEndPoint\&.delete ( username,  car_id)\fC [static]\fP"

.PP
.nf
Delete a car from a driver's info
.fi
.PP
 
.PP
Definition at line 139 of file DriversHandler\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
