.TH "server.src.handlers.PositionHandler" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.handlers.PositionHandler \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPositionAPI\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBPOSITION_BLUEPRINT\fP = Blueprint('position', __name__)"
.br
.ti -1c
.RI "\fBPOSITION_VIEW\fP = PositionAPI\&.as_view('position_api')"
.br
.ti -1c
.RI "\fBview_func\fP"
.br
.ti -1c
.RI "\fBmethods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Handlers related with the position of users
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "server\&.src\&.handlers\&.PositionHandler\&.methods"

.PP
Definition at line 95 of file PositionHandler\&.py\&.
.SS "server\&.src\&.handlers\&.PositionHandler\&.POSITION_BLUEPRINT = Blueprint('position', __name__)"

.PP
Definition at line 11 of file PositionHandler\&.py\&.
.SS "server\&.src\&.handlers\&.PositionHandler\&.POSITION_VIEW = PositionAPI\&.as_view('position_api')"

.PP
Definition at line 89 of file PositionHandler\&.py\&.
.SS "server\&.src\&.handlers\&.PositionHandler\&.view_func"

.PP
Definition at line 94 of file PositionHandler\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
