.TH "server.src.services.shared_server" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.services.shared_server \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBregister_user\fP (userdata)"
.br
.ti -1c
.RI "def \fBremove_user\fP (user_id)"
.br
.ti -1c
.RI "def \fBupdate_user_data\fP (user_id, data)"
.br
.ti -1c
.RI "def \fBregister_car\fP (user_id, data)"
.br
.ti -1c
.RI "def \fBdelete_car\fP (user_id, car_id)"
.br
.ti -1c
.RI "def \fBvalidate_user\fP (username, password)"
.br
.ti -1c
.RI "def \fBregister_trip\fP (data)"
.br
.ti -1c
.RI "def \fBestimate_trip_cost\fP (data)"
.br
.ti -1c
.RI "def \fBget_data\fP (user_id)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Services used from the shared server
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "def server\&.src\&.services\&.shared_server\&.delete_car ( user_id,  car_id)"

.PP
.nf
Delete driver's car info in the shared server
.fi
.PP
 
.PP
Definition at line 35 of file shared_server\&.py\&.
.SS "def server\&.src\&.services\&.shared_server\&.estimate_trip_cost ( data)"

.PP
.nf
Obtain an estimation of the cost of a trip to be made
.fi
.PP
 
.PP
Definition at line 54 of file shared_server\&.py\&.
.SS "def server\&.src\&.services\&.shared_server\&.get_data ( user_id)"

.PP
.nf
Get user's data from the shared server
.fi
.PP
 
.PP
Definition at line 61 of file shared_server\&.py\&.
.SS "def server\&.src\&.services\&.shared_server\&.register_car ( user_id,  data)"

.PP
.nf
Register driver's car info in the shared server
.fi
.PP
 
.PP
Definition at line 30 of file shared_server\&.py\&.
.SS "def server\&.src\&.services\&.shared_server\&.register_trip ( data)"

.PP
.nf
Register a trip in the shared server that has already finished
.fi
.PP
 
.PP
Definition at line 47 of file shared_server\&.py\&.
.SS "def server\&.src\&.services\&.shared_server\&.register_user ( userdata)"

.PP
.nf
Registers a user in the shared server
.fi
.PP
 
.PP
Definition at line 7 of file shared_server\&.py\&.
.SS "def server\&.src\&.services\&.shared_server\&.remove_user ( user_id)"

.PP
.nf
Erases a user's account in the shared server
.fi
.PP
 
.PP
Definition at line 13 of file shared_server\&.py\&.
.SS "def server\&.src\&.services\&.shared_server\&.update_user_data ( user_id,  data)"

.PP
.nf
Update user's info in the shared server
.fi
.PP
 
.PP
Definition at line 20 of file shared_server\&.py\&.
.SS "def server\&.src\&.services\&.shared_server\&.validate_user ( username,  password)"

.PP
.nf
Validate user's credentials in the shared server
.fi
.PP
 
.PP
Definition at line 40 of file shared_server\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
