.TH "server.src.handlers.RequestHandler" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.handlers.RequestHandler \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRequestCancellation\fP"
.br
.ti -1c
.RI "class \fBRequestSubmission\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBREQUESTS_BLUEPRINT\fP = Blueprint('requests', __name__)"
.br
.ti -1c
.RI "\fBREQUESTS_SUBMISSION_VIEW\fP = RequestSubmission\&.as_view('request_submission')"
.br
.ti -1c
.RI "\fBREQUEST_CANCELLATION_VIEW\fP = RequestCancellation\&.as_view('request_cancellation')"
.br
.ti -1c
.RI "\fBview_func\fP"
.br
.ti -1c
.RI "\fBmethods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Handlers related with rider's specific functionality
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "server\&.src\&.handlers\&.RequestHandler\&.methods"

.PP
Definition at line 232 of file RequestHandler\&.py\&.
.SS "server\&.src\&.handlers\&.RequestHandler\&.REQUEST_CANCELLATION_VIEW = RequestCancellation\&.as_view('request_cancellation')"

.PP
Definition at line 226 of file RequestHandler\&.py\&.
.SS "server\&.src\&.handlers\&.RequestHandler\&.REQUESTS_BLUEPRINT = Blueprint('requests', __name__)"

.PP
Definition at line 16 of file RequestHandler\&.py\&.
.SS "server\&.src\&.handlers\&.RequestHandler\&.REQUESTS_SUBMISSION_VIEW = RequestSubmission\&.as_view('request_submission')"

.PP
Definition at line 225 of file RequestHandler\&.py\&.
.SS "server\&.src\&.handlers\&.RequestHandler\&.view_func"

.PP
Definition at line 231 of file RequestHandler\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
