.TH "server.src.models.BlacklistToken" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.models.BlacklistToken \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBtoken\fP)"
.br
.ti -1c
.RI "def \fB__repr__\fP (self)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBis_blacklisted\fP (\fBtoken\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtoken\fP"
.br
.ti -1c
.RI "\fBblacklisted_on\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Token Model for storing invalid JWT

.fi
.PP
 
.PP
Definition at line 89 of file models\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def server\&.src\&.models\&.BlacklistToken\&.__init__ ( self,  token)"

.PP
Definition at line 94 of file models\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def server\&.src\&.models\&.BlacklistToken\&.__repr__ ( self)"

.PP
Definition at line 98 of file models\&.py\&.
.SS "def server\&.src\&.models\&.BlacklistToken\&.is_blacklisted ( token)\fC [static]\fP"

.PP
.nf
Returns true if a user has logged out using this token
.fi
.PP
 
.PP
Definition at line 102 of file models\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "server\&.src\&.models\&.BlacklistToken\&.blacklisted_on"

.PP
Definition at line 96 of file models\&.py\&.
.SS "server\&.src\&.models\&.BlacklistToken\&.token"

.PP
Definition at line 95 of file models\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
