.TH "server.src.mixins.AuthenticationMixin" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.mixins.AuthenticationMixin \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAuthenticator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Mixins for authentication stuff
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
