.TH "server.src.exceptions.InvalidTokenException" 3 "Mon Nov 6 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.exceptions.InvalidTokenException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.PP
Inherited by \fBserver\&.src\&.exceptions\&.BlacklistedTokenException\fP, \fBserver\&.src\&.exceptions\&.ExpiredTokenException\fP, and \fBserver\&.src\&.exceptions\&.SignatureException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBtoken\fP, message='')"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtoken\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
This generic exception raised on a invalid token
.fi
.PP
 
.PP
Definition at line 2 of file exceptions\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def server\&.src\&.exceptions\&.InvalidTokenException\&.__init__ ( self,  token,  message = \fC''\fP)"

.PP
Definition at line 5 of file exceptions\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "server\&.src\&.exceptions\&.InvalidTokenException\&.token"

.PP
Definition at line 10 of file exceptions\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
