.TH "server.src.handlers.DriversHandler.AvailableEndpoint" 3 "Mon Nov 6 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.handlers.DriversHandler.AvailableEndpoint \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MethodView\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBget\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 81 of file DriversHandler\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def server\&.src\&.handlers\&.DriversHandler\&.AvailableEndpoint\&.get ( self)"

.PP
Definition at line 82 of file DriversHandler\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
