.TH "server.src.handlers" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.handlers \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBDriversHandler\fP"
.br
.ti -1c
.RI " \fBPositionHandler\fP"
.br
.ti -1c
.RI " \fBRegisterHandler\fP"
.br
.ti -1c
.RI " \fBRequestHandler\fP"
.br
.ti -1c
.RI " \fBSecurityHandler\fP"
.br
.ti -1c
.RI " \fBTokenRegistrationHandler\fP"
.br
.ti -1c
.RI " \fBTripHandler\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
