.TH "server.src.mixins.AuthenticationMixin.Authenticator" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.mixins.AuthenticationMixin.Authenticator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBauthenticate\fP (auth_header)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Utility class for anything related with authentication
.fi
.PP
 
.PP
Definition at line 7 of file AuthenticationMixin\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def server\&.src\&.mixins\&.AuthenticationMixin\&.Authenticator\&.authenticate ( auth_header)\fC [static]\fP"

.PP
.nf
Gets the correspondig user given the auth header, returns error_message if any
.fi
.PP
 
.PP
Definition at line 11 of file AuthenticationMixin\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
