.TH "server.src.exceptions.ExpiredTokenException" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.exceptions.ExpiredTokenException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBserver\&.src\&.exceptions\&.InvalidTokenException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBtoken\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
.nf
This exception is raised if a token that is trying to be used has expired
.fi
.PP
 
.PP
Definition at line 31 of file exceptions\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def server\&.src\&.exceptions\&.ExpiredTokenException\&.__init__ ( self,  token)"

.PP
Definition at line 34 of file exceptions\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
