.TH "server.src.handlers.RegisterHandler.RegisterAPI" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.handlers.RegisterHandler.RegisterAPI \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MethodView\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBpost\fP ()"
.br
.ti -1c
.RI "def \fBdelete\fP (username)"
.br
.ti -1c
.RI "def \fBput\fP (username)"
.br
.ti -1c
.RI "def \fBget\fP (username)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Handler for registration related API
.fi
.PP
 
.PP
Definition at line 14 of file RegisterHandler\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def server\&.src\&.handlers\&.RegisterHandler\&.RegisterAPI\&.delete ( username)\fC [static]\fP"

.PP
.nf
Endpoint for erasign an user
.fi
.PP
 
.PP
Definition at line 79 of file RegisterHandler\&.py\&.
.SS "def server\&.src\&.handlers\&.RegisterHandler\&.RegisterAPI\&.get ( username)\fC [static]\fP"

.PP
.nf
Get a user info
.fi
.PP
 
.PP
Definition at line 188 of file RegisterHandler\&.py\&.
.SS "def server\&.src\&.handlers\&.RegisterHandler\&.RegisterAPI\&.post ()\fC [static]\fP"

.PP
.nf
Endpoint for signing up
.fi
.PP
 
.PP
Definition at line 18 of file RegisterHandler\&.py\&.
.SS "def server\&.src\&.handlers\&.RegisterHandler\&.RegisterAPI\&.put ( username)\fC [static]\fP"

.PP
.nf
Endpoint for modifying an user's general info
.fi
.PP
 
.PP
Definition at line 134 of file RegisterHandler\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
