.TH "server.src.models" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.models \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBlacklistToken\fP"
.br
.ti -1c
.RI "class \fBUser\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBSECRET_KEY\fP = os\&.environ\&.get('SECRET_KEY', 'key')"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Entitys saved in the db
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "server\&.src\&.models\&.SECRET_KEY = os\&.environ\&.get('SECRET_KEY', 'key')"

.PP
Definition at line 11 of file models\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
