.TH "server.src.handlers.RequestHandler.RequestCancellation" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.handlers.RequestHandler.RequestCancellation \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MethodView\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBdelete\fP (requestID)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Handler for request cancellation
.fi
.PP
 
.PP
Definition at line 154 of file RequestHandler\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def server\&.src\&.handlers\&.RequestHandler\&.RequestCancellation\&.delete ( requestID)\fC [static]\fP"

.PP
.nf
Endpoint for cancelling an unstarted trip a.k.a a request made that was matched
.fi
.PP
 
.PP
Definition at line 158 of file RequestHandler\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
