.TH "server.src.handlers.TokenRegistrationHandler" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.handlers.TokenRegistrationHandler \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPushNotificationAPI\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBTOKEN_MANIPULATION_BLUEPRINT\fP = Blueprint('token_push_notifications', __name__)"
.br
.ti -1c
.RI "\fBTOKEN_MANIPULATION_VIEW\fP = PushNotificationAPI\&.as_view('push_notification_api')"
.br
.ti -1c
.RI "\fBview_func\fP"
.br
.ti -1c
.RI "\fBmethods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Handlers for manipulating the firebase token
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "server\&.src\&.handlers\&.TokenRegistrationHandler\&.methods"

.PP
Definition at line 87 of file TokenRegistrationHandler\&.py\&.
.SS "server\&.src\&.handlers\&.TokenRegistrationHandler\&.TOKEN_MANIPULATION_BLUEPRINT = Blueprint('token_push_notifications', __name__)"

.PP
Definition at line 11 of file TokenRegistrationHandler\&.py\&.
.SS "server\&.src\&.handlers\&.TokenRegistrationHandler\&.TOKEN_MANIPULATION_VIEW = PushNotificationAPI\&.as_view('push_notification_api')"

.PP
Definition at line 81 of file TokenRegistrationHandler\&.py\&.
.SS "server\&.src\&.handlers\&.TokenRegistrationHandler\&.view_func"

.PP
Definition at line 86 of file TokenRegistrationHandler\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
