.TH "server.src.controllers.AppController" 3 "Sat Sep 9 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.controllers.AppController \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBindex\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def server\&.src\&.controllers\&.AppController\&.index ()"

.PP
Definition at line 1 of file AppController\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
