.TH "server.src.handlers.SecurityHandler.SecurityAPI" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.handlers.SecurityHandler.SecurityAPI \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MethodView\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBpost\fP ()"
.br
.ti -1c
.RI "def \fBdelete\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Handler for login/logout related API
.fi
.PP
 
.PP
Definition at line 15 of file SecurityHandler\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def server\&.src\&.handlers\&.SecurityHandler\&.SecurityAPI\&.delete ()\fC [static]\fP"

.PP
.nf
Endpoint for loging out a user, blacklists authentication token
.fi
.PP
 
.PP
Definition at line 81 of file SecurityHandler\&.py\&.
.SS "def server\&.src\&.handlers\&.SecurityHandler\&.SecurityAPI\&.post ()\fC [static]\fP"

.PP
.nf
Endpoint for loging in a user, returns authentication token
.fi
.PP
 
.PP
Definition at line 20 of file SecurityHandler\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
