.TH "server.src.handlers.DriversHandler" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.handlers.DriversHandler \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAvailableEndpoint\fP"
.br
.ti -1c
.RI "class \fBCarDeleteEndPoint\fP"
.br
.ti -1c
.RI "class \fBCarRegisterEndPoint\fP"
.br
.ti -1c
.RI "class \fBDriversAPI\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBDRIVERS_BLUEPRINT\fP = Blueprint('drivers', __name__)"
.br
.ti -1c
.RI "\fBDRIVERS_VIEW\fP = DriversAPI\&.as_view('drivers_api')"
.br
.ti -1c
.RI "\fBAVAILABLE_VIEW\fP = AvailableEndpoint\&.as_view('available_endpoint')"
.br
.ti -1c
.RI "\fBCAR_REGISTER_VIEW\fP = CarRegisterEndPoint\&.as_view('car_register_endpoint')"
.br
.ti -1c
.RI "\fBCAR_DELETE_VIEW\fP = CarDeleteEndPoint\&.as_view('car_delete_endpoint')"
.br
.ti -1c
.RI "\fBview_func\fP"
.br
.ti -1c
.RI "\fBmethods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Handlers related with driver's specific functionality
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "server\&.src\&.handlers\&.DriversHandler\&.AVAILABLE_VIEW = AvailableEndpoint\&.as_view('available_endpoint')"

.PP
Definition at line 215 of file DriversHandler\&.py\&.
.SS "server\&.src\&.handlers\&.DriversHandler\&.CAR_DELETE_VIEW = CarDeleteEndPoint\&.as_view('car_delete_endpoint')"

.PP
Definition at line 217 of file DriversHandler\&.py\&.
.SS "server\&.src\&.handlers\&.DriversHandler\&.CAR_REGISTER_VIEW = CarRegisterEndPoint\&.as_view('car_register_endpoint')"

.PP
Definition at line 216 of file DriversHandler\&.py\&.
.SS "server\&.src\&.handlers\&.DriversHandler\&.DRIVERS_BLUEPRINT = Blueprint('drivers', __name__)"

.PP
Definition at line 11 of file DriversHandler\&.py\&.
.SS "server\&.src\&.handlers\&.DriversHandler\&.DRIVERS_VIEW = DriversAPI\&.as_view('drivers_api')"

.PP
Definition at line 214 of file DriversHandler\&.py\&.
.SS "server\&.src\&.handlers\&.DriversHandler\&.methods"

.PP
Definition at line 223 of file DriversHandler\&.py\&.
.SS "server\&.src\&.handlers\&.DriversHandler\&.view_func"

.PP
Definition at line 222 of file DriversHandler\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
