.TH "server.src.handlers.RegisterHandler" 3 "Mon Nov 6 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.handlers.RegisterHandler \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRegisterAPI\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBregistration_blueprint\fP = Blueprint('users', __name__)"
.br
.ti -1c
.RI "\fBregistration_view\fP = RegisterAPI\&.as_view('registration_api')"
.br
.ti -1c
.RI "\fBview_func\fP"
.br
.ti -1c
.RI "\fBmethods\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "server\&.src\&.handlers\&.RegisterHandler\&.methods"

.PP
Definition at line 240 of file RegisterHandler\&.py\&.
.SS "server\&.src\&.handlers\&.RegisterHandler\&.registration_blueprint = Blueprint('users', __name__)"

.PP
Definition at line 9 of file RegisterHandler\&.py\&.
.SS "server\&.src\&.handlers\&.RegisterHandler\&.registration_view = RegisterAPI\&.as_view('registration_api')"

.PP
Definition at line 234 of file RegisterHandler\&.py\&.
.SS "server\&.src\&.handlers\&.RegisterHandler\&.view_func"

.PP
Definition at line 239 of file RegisterHandler\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
