.TH "server.src.handlers.PositionHandler.PositionAPI" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.handlers.PositionHandler.PositionAPI \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MethodView\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBput\fP (username)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Handler for position related API
.fi
.PP
 
.PP
Definition at line 14 of file PositionHandler\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def server\&.src\&.handlers\&.PositionHandler\&.PositionAPI\&.put ( username)\fC [static]\fP"

.PP
.nf
Endpoint for Updating a user position
.fi
.PP
 
.PP
Definition at line 18 of file PositionHandler\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
