.TH "server.src.handlers.DriversHandler.CarRegisterEndPoint" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.handlers.DriversHandler.CarRegisterEndPoint \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MethodView\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBpost\fP (username)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
View used for registering car information corresponding to a driver
.fi
.PP
 
.PP
Definition at line 77 of file DriversHandler\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def server\&.src\&.handlers\&.DriversHandler\&.CarRegisterEndPoint\&.post ( username)\fC [static]\fP"

.PP
.nf
Registering a car for a specific driver
.fi
.PP
 
.PP
Definition at line 81 of file DriversHandler\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
