.TH "server.src.handlers.DriversHandler" 3 "Mon Nov 6 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.handlers.DriversHandler \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAvailableEndpoint\fP"
.br
.ti -1c
.RI "class \fBDriversAPI\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBdrivers_blueprint\fP = Blueprint('drivers', __name__)"
.br
.ti -1c
.RI "\fBdrivers_view\fP = DriversAPI\&.as_view('drivers_api')"
.br
.ti -1c
.RI "\fBavailable_view\fP = AvailableEndpoint\&.as_view('available_endpoint')"
.br
.ti -1c
.RI "\fBview_func\fP"
.br
.ti -1c
.RI "\fBmethods\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "server\&.src\&.handlers\&.DriversHandler\&.available_view = AvailableEndpoint\&.as_view('available_endpoint')"

.PP
Definition at line 97 of file DriversHandler\&.py\&.
.SS "server\&.src\&.handlers\&.DriversHandler\&.drivers_blueprint = Blueprint('drivers', __name__)"

.PP
Definition at line 9 of file DriversHandler\&.py\&.
.SS "server\&.src\&.handlers\&.DriversHandler\&.drivers_view = DriversAPI\&.as_view('drivers_api')"

.PP
Definition at line 96 of file DriversHandler\&.py\&.
.SS "server\&.src\&.handlers\&.DriversHandler\&.methods"

.PP
Definition at line 103 of file DriversHandler\&.py\&.
.SS "server\&.src\&.handlers\&.DriversHandler\&.view_func"

.PP
Definition at line 102 of file DriversHandler\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
