.TH "server.src.handlers.SecurityHandler" 3 "Mon Nov 6 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.handlers.SecurityHandler \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSecurityAPI\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBsecurity_blueprint\fP = Blueprint('security', __name__)"
.br
.ti -1c
.RI "\fBsecurity_view\fP = SecurityAPI\&.as_view('security_api')"
.br
.ti -1c
.RI "\fBview_func\fP"
.br
.ti -1c
.RI "\fBmethods\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "server\&.src\&.handlers\&.SecurityHandler\&.methods"

.PP
Definition at line 127 of file SecurityHandler\&.py\&.
.SS "server\&.src\&.handlers\&.SecurityHandler\&.security_blueprint = Blueprint('security', __name__)"

.PP
Definition at line 10 of file SecurityHandler\&.py\&.
.SS "server\&.src\&.handlers\&.SecurityHandler\&.security_view = SecurityAPI\&.as_view('security_api')"

.PP
Definition at line 121 of file SecurityHandler\&.py\&.
.SS "server\&.src\&.handlers\&.SecurityHandler\&.view_func"

.PP
Definition at line 126 of file SecurityHandler\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
