.TH "server.src.handlers.SecurityHandler.SecurityAPI" 3 "Mon Nov 6 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.handlers.SecurityHandler.SecurityAPI \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MethodView\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBpost\fP (self)"
.br
.ti -1c
.RI "def \fBdelete\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Handler for login/logout related API
.fi
.PP
 
.PP
Definition at line 12 of file SecurityHandler\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def server\&.src\&.handlers\&.SecurityHandler\&.SecurityAPI\&.delete ( self)"

.PP
Definition at line 72 of file SecurityHandler\&.py\&.
.SS "def server\&.src\&.handlers\&.SecurityHandler\&.SecurityAPI\&.post ( self)"

.PP
Definition at line 15 of file SecurityHandler\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
