.TH "server.src.services.push_notifications" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.services.push_notifications \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBsend_push_notifications\fP (username, message_body, data_message)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBFIREBASE_KEY\fP = os\&.environ['FIREBASE_KEY']"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def server\&.src\&.services\&.push_notifications\&.send_push_notifications ( username,  message_body,  data_message)"

.PP
Definition at line 11 of file push_notifications\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "server\&.src\&.services\&.push_notifications\&.FIREBASE_KEY = os\&.environ['FIREBASE_KEY']"

.PP
Definition at line 8 of file push_notifications\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
