.TH "server.src.handlers.RequestHandler.RequestSubmission" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.handlers.RequestHandler.RequestSubmission \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MethodView\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBpost\fP (username)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Handler for request submission
.fi
.PP
 
.PP
Definition at line 19 of file RequestHandler\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def server\&.src\&.handlers\&.RequestHandler\&.RequestSubmission\&.post ( username)\fC [static]\fP"

.PP
.nf
Endpoint for requesting a ride
.fi
.PP
 
.PP
Definition at line 23 of file RequestHandler\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
