.TH "server.src.services.google_maps" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.services.google_maps \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBget_directions\fP (data)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBGOOGLE_KEY\fP = os\&.environ['GOOGLE_KEY']"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def server\&.src\&.services\&.google_maps\&.get_directions ( data)"

.PP
Definition at line 7 of file google_maps\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "server\&.src\&.services\&.google_maps\&.GOOGLE_KEY = os\&.environ['GOOGLE_KEY']"

.PP
Definition at line 4 of file google_maps\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
