.TH "server.src.handlers.RegisterHandler.RegisterAPI" 3 "Mon Nov 6 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.handlers.RegisterHandler.RegisterAPI \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MethodView\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBpost\fP (self)"
.br
.ti -1c
.RI "def \fBdelete\fP (self, username)"
.br
.ti -1c
.RI "def \fBput\fP (self, username)"
.br
.ti -1c
.RI "def \fBget\fP (self, username)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Handler for registration related API
.fi
.PP
 
.PP
Definition at line 11 of file RegisterHandler\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def server\&.src\&.handlers\&.RegisterHandler\&.RegisterAPI\&.delete ( self,  username)"

.PP
Definition at line 67 of file RegisterHandler\&.py\&.
.SS "def server\&.src\&.handlers\&.RegisterHandler\&.RegisterAPI\&.get ( self,  username)"

.PP
Definition at line 205 of file RegisterHandler\&.py\&.
.SS "def server\&.src\&.handlers\&.RegisterHandler\&.RegisterAPI\&.post ( self)"

.PP
Definition at line 14 of file RegisterHandler\&.py\&.
.SS "def server\&.src\&.handlers\&.RegisterHandler\&.RegisterAPI\&.put ( self,  username)"

.PP
Definition at line 137 of file RegisterHandler\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
