.TH "server.src.mixins.DriversMixin.DriversMixin" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server.src.mixins.DriversMixin.DriversMixin \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBget_available_drivers\fP ()"
.br
.ti -1c
.RI "def \fBget_positions\fP (drivers_names)"
.br
.ti -1c
.RI "def \fBdistance\fP (origin, destination)"
.br
.ti -1c
.RI "def \fBget_closer_driver\fP (location)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Utility class for anything related with drivers
.fi
.PP
 
.PP
Definition at line 7 of file DriversMixin\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def server\&.src\&.mixins\&.DriversMixin\&.DriversMixin\&.distance ( origin,  destination)\fC [static]\fP"

.PP
Definition at line 23 of file DriversMixin\&.py\&.
.SS "def server\&.src\&.mixins\&.DriversMixin\&.DriversMixin\&.get_available_drivers ()\fC [static]\fP"

.PP
.nf
Gets the ids of all the available drivers
.fi
.PP
 
.PP
Definition at line 11 of file DriversMixin\&.py\&.
.SS "def server\&.src\&.mixins\&.DriversMixin\&.DriversMixin\&.get_closer_driver ( location)\fC [static]\fP"

.PP
.nf
Get the id of the driver which is closer to the given location
.fi
.PP
 
.PP
Definition at line 40 of file DriversMixin\&.py\&.
.SS "def server\&.src\&.mixins\&.DriversMixin\&.DriversMixin\&.get_positions ( drivers_names)\fC [static]\fP"

.PP
Definition at line 18 of file DriversMixin\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
