.TH "src/handlers/TokenRegistrationHandler.py" 3 "Thu Nov 30 2017" "Version 1.0.0" "FIUBER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/handlers/TokenRegistrationHandler.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBserver\&.src\&.handlers\&.TokenRegistrationHandler\&.PushNotificationAPI\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBserver\&.src\&.handlers\&.TokenRegistrationHandler\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBserver\&.src\&.handlers\&.TokenRegistrationHandler\&.TOKEN_MANIPULATION_BLUEPRINT\fP = Blueprint('token_push_notifications', __name__)"
.br
.ti -1c
.RI "\fBserver\&.src\&.handlers\&.TokenRegistrationHandler\&.TOKEN_MANIPULATION_VIEW\fP = PushNotificationAPI\&.as_view('push_notification_api')"
.br
.ti -1c
.RI "\fBserver\&.src\&.handlers\&.TokenRegistrationHandler\&.view_func\fP"
.br
.ti -1c
.RI "\fBserver\&.src\&.handlers\&.TokenRegistrationHandler\&.methods\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FIUBER from the source code\&.
